language: go

sudo: required

node_js:
  - 1.12.x

services:
  - docker


install:
  - go install

script:
  - make test

after_success:
  - set -e
  - if [ -z "${DOCKER_PASS}" ]; then echo "Build triggered by external PR. Skipping docker push" && exit 0; fi
  - make login
  - make image-build
  - make push