language: go

sudo: required

go:
  - 1.12.x

services:
  - docker

install:
  - go install

script:
  - go test .
  - docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}" registry.sensetime.com;
#  - make login
  - make image-build
  - make push