language: go

sudo: required

go:
  - 1.12.x

services:
  - docker


install:
  - go install

env:
  - IMAGE=

script:
  - go test .

after_success:
#  - docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}" registry.sensetime.com;
  - make login
  - make build
  - make push